export const INIT_SURVEY = 'INIT_SURVEY';
export const STOP_SURVEY = 'STOP_SURVEY';
export const FINISH_SURVEY = 'FINISH_SURVEY';
export const CONTINUE_SURVEY = 'CONTINUE_SURVEY';

export const PREV_QUESTION = 'PREV_QUESTION';
export const VERIFY_QUESTION = 'VERIFY_QUESTION';
export const SKIP_QUESTION = 'SKIP_QUESTION';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const ANSWERED_QUESTION = 'ANSWERED_QUESTION';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
